
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'aprcot_DW'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

on-run-start:
    - '{{create_udfs()}}'


# Configuring global variables
vars:
    aprcot_DW:
        source_table: '_dbt_source_relation'
        f5500_id: 'f5500_id'
        f5500_ein: 'ein'
        f5500_plan_effective_date: 'plan_effective_date'
        f5500_plan_name: 'plan_name'
        f5500_date_received: 'date_received'
        f5500_naics_code: 'naics_code'
        f5500_sponsor_corporate_name: 'sponsor_corporate_name'
        f5500_doing_busines_as_name: 'doing_busines_as_name'
        f5500_boy_partcp_count: 'boy_partcp_count'
        f5500_is_boy_partcp_count_active_only: 'is_boy_partcp_count_active_only'
        f5500_eoy_active_partcp_count: 'eoy_active_partcp_count'
        f5500_pre_2009_mailing_address: 'pre_2009_mailing_address'
        f5500_pre_2009_mailing_city: 'pre_2009_mailing_city'
        f5500_pre_2009_state: 'pre_2009_state'
        f5500_pre_2009_zip_code: 'pre_2009_zip_code'
        f5500_pre_2009_loc_address: 'pre_2009_loc_address'
        f5500_us_mail_address1: 'us_mail_address1'
        f5500_us_mail_address2: 'us_mail_address2'
        f5500_us_mail_city: 'us_mail_city'
        f5500_us_mail_state: 'us_mail_state'
        f5500_us_mail_zip_code: 'us_mail_zip_code'
        f5500_us_loc_address1: 'us_loc_address1'
        f5500_us_loc_address2: 'us_loc_address2'
        f5500_us_loc_city: 'us_loc_city'
        f5500_us_loc_state: 'us_loc_state'
        f5500_us_loc_zip_code: 'us_loc_zip_code'
        f5500_foreign_mail_city: 'foreign_mail_city'
        f5500_foreign_mail_province_or_state: 'foreign_mail_province_or_state'
        f5500_foreign_mail_country: 'foreign_mail_country'
        f5500_foreign_mail_postal_code: 'foreign_mail_postal_code'
        f5500_contact_phone_num: 'contact_phone_num'
        f5500_contact_name: 'contact_name'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    aprcot_DW:
        src_pre_processing:
            materialized: view
        dim_tables:
            materialized: view
        fct_tables:
            materialized: view
